### ISSUE TITLE
more runs in the database than in archive

### ISSUE THREAD

**Issue by tybritten** [nyaruka/rp-archiver#41]
So we've been getting this error recently and I can't seem to figure out why. Wouldn't archiver update the archive so then it should have a matching number of records before it tries to delete the records from the db?

Its only on flow run archives and only on dailys

**Comment by nicpottier** [comment]
Hrmm, maybe that's the right thing but really this is an assertion more than anything. We really shouldn't ever be in a case where a daily archive built a few minutes ago has fewer items than the DB, so that's an indication of some assumptions we are making being incorrect.

So would be curious for you to look into that archive and the DB records to figure out WHY they are different so we have an understanding of what is happening there.

**Comment by tybritten** [comment]
so i've started digging through the missing flowruns and nothing stands out besides the fact that many are scheduled flows (for like 3am our time). One thing i was looking at- the start and end ranges being passed to the sql query..it doesn't appear that they're trimming the time off? Shouldn't it set the time to 00:00 UTC?

**Comment by nicpottier** [comment]
Hrmm, that sounds suspicious, what dates are these? Aren't the start and end dates created with 0s already:
    https://github.com/nyaruka/rp-archiver/blob/master/archiver.go#L223

Or are you talking about something else?
